# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 804a257b0fe701d72938aa8ab85e202125b6a9a08d4a1dde6b0d323779e90e8535c33369384d915f5bc88d351aa9ac9a4e57a2665856950653e0bac6f206c39d

test:
  secret_key_base: 3e05c338d5deb643976e5d5c72a60d5a54cfe6f7d91a759aa2bfe62aa55fbf097fa42e550b4de0af4ae28a222ad439ce78d572d8f98cce180666da728e15e0c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
